# Mastering pandas book

In [1]:
import numpy as np

## NumPy array creation
### NumPy arrays via `numpy.array`

In [7]:
# 1 dimensional array
ar1 = np.array([0,1,2,3])

# 2 dimensional array
ar2 = np.array([[0,3,5], [2,8,7]])

print("Array 1: ", ar1)
print("Array 2: ", ar2)
print("Array shape: ", ar2.shape)
print("Array dimension: ", ar2.ndim)

Array 1:  [0 1 2 3]
Array 2:  [[0 3 5]
 [2 8 7]]
Array shape:  (2, 3)
Array dimension:  2


### NumPy array via `numpy.arange`

In [9]:
# Python's range function
ar3 = np.arange(12)
print(ar3)

ar4 = np.arange(3, 10, 3)
print(ar4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[3 6 9]


### NumPy array via `numpy.linspace`

In [10]:
ar5 = np.linspace(0, 2.0/3, 4)
print(ar5)

[ 0.          0.22222222  0.44444444  0.66666667]


## NumPy array via various other functions
### `numpy.ones`

In [11]:
ar7 = np.ones((2, 3, 2))
print(ar7)

[[[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]]


### `numpy.zeros`

In [12]:
ar8 = np.zeros((4, 2))
print(ar8)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


### `numpy.eye`

In [13]:
ar9 = np.eye(3)
print(ar9)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### `numpy.diag`

In [14]:
ar10 = np.diag((2, 1, 4, 6))
print(ar10)

[[2 0 0 0]
 [0 1 0 0]
 [0 0 4 0]
 [0 0 0 6]]


### `numpy.random.rand`

In [26]:
np.random.seed(100)
ar11 = np.random.rand(3)
print(ar11)

[ 0.54340494  0.27836939  0.42451759]


In [25]:
ar12 = np.random.rand(5)
print(ar12)

[ 0.10837689  0.21969749  0.97862378  0.81168315  0.17194101]


### `numpy.empty`
Create an uninitialized array.

In [27]:
ar13 = np.empty((3, 2))
print(ar13)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


### `numpy.tile`

In [29]:
np.array([[1, 2], [6, 7]])

array([[1, 2],
       [6, 7]])

In [33]:
np.tile(np.array([[1, 2], [6, 7]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [34]:
np.tile(np.array([[1, 2], [6, 7]]), (2, 2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

## NumPy datatypes

In [37]:
ar = np.array([2, -1, 6, 3], dtype='float')
print(ar)

[ 2. -1.  6.  3.]


In [38]:
ar.dtype

dtype('float64')

In [40]:
ar = np.array([2, 4, 6, 8])
ar.dtype

dtype('int64')

In [41]:
ar = np.array([2., 4, 6, 8])
ar.dtype

dtype('float64')

The default `dtype` in NumPy is `float`.

In [42]:
sar = np.array(['Goodbye', 'Hello', 'Bye', 'GoodNight'])
sar.dtype

dtype('<U9')

In [43]:
bar =  np.array([True, False, True])
bar.dtype

dtype('bool')

Changing the data type of `ndarray`

In [44]:
f_ar = np.array([3, -2, 8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [45]:
f_ar.astype(int)

array([ 3, -2,  8])

## NumPy indexing and slicing